#lang sicp
(define (square x)
  (* x x))
(define (sum-of-squares x y)
  (+ (square x) (square y)))
(define (greater-sum x y z)
  (cond ((and (> x y) (> z y)) (sum-of-squares x z))
        ((and (> y x) (> z x)) (sum-of-squares y z))
        (else (sum-of-squares x y))))
(greater-sum 1 3 4)